# Generated by Django 4.2.2 on 2023-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='last_name',
        ),
        migrations.AddField(
            model_name='comment',
            name='about',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='comment',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
