# Generated by Django 4.2.2 on 2023-07-10 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_post_alter_comment_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(),
        ),
    ]
