# Generated by Django 4.2.2 on 2023-07-10 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
